### ISSUE TITLE
Date range shown in graphs should be adjustable

### ISSUE THREAD

**Issue by jrnorth** [dhganey/mwa-capstone#14]
Dr. Jacobs mentioned that in the current version of the site, there's a slider you can use to adjust the date range shown in the graph. He said that he'd like a similar feature on the graphs in our version of the site. I'm not sure if Highcharts (the JS charting library we're using right now) has this capability, so we may need to explore other options (such as amCharts or Google Charts).

**Comment by dhganey** [comment]
Ben, am I correct in thinking you were looking into this?
