### ISSUE TITLE
Error when fetching ranges

### ISSUE THREAD

**Issue by ryandougherty** [dhganey/mwa-capstone#20]
==> default: Traceback (most recent call last):
==> default:   File "/mnt/eorlive_prototype/flask/lib/python3.4/site-packages/flask/app.py", line 1836, in __call__
==> default:     return self.wsgi_app(environ, start_response)
==> default:   File "/mnt/eorlive_prototype/flask/lib/python3.4/site-packages/flask/app.py", line 1820, in wsgi_app
==> default:     response = self.make_response(self.handle_exception(e))
==> default:   File "/mnt/eorlive_prototype/flask/lib/python3.4/site-packages/flask/app.py", line 1403, in handle_exception
==> default:     reraise(exc_type, exc_value, tb)
==> default:   File "/mnt/eorlive_prototype/flask/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
==> default:     raise value
==> default:   File "/mnt/eorlive_prototype/flask/lib/python3.4/site-packages/flask/app.py", line 1817, in wsgi_app
==> default:     response = self.full_dispatch_request()
==> default:   File "/mnt/eorlive_prototype/flask/lib/python3.4/site-packages/flask/app.py", line 1477, in full_dispatch_request
==> default:     rv = self.handle_user_exception(e)
==> default:   File "/mnt/eorlive_prototype/flask/lib/python3.4/site-packages/flask/app.py", line 1381, in handle_user_exception
==> default:     reraise(exc_type, exc_value, tb)
==> default:   File "/mnt/eorlive_prototype/flask/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
==> default:     raise value
==> default:   File "/mnt/eorlive_prototype/flask/lib/python3.4/site-packages/flask/app.py", line 1475, in full_dispatch_request
==> default:     rv = self.dispatch_request()
==> default:   File "/mnt/eorlive_prototype/flask/lib/python3.4/site-packages/flask/app.py", line 1461, in dispatch_request
==> default:     return self.view_functions[rule.endpoint](**req.view_args)
==> default:   File "/mnt/eorlive_prototype/app/views.py", line 125, in histogram_data
==> default:     ORDER BY starttime ASC'''.format(start_gps, end_gps)).fetchall()
==> default:   File "/mnt/eorlive_prototype/flask/lib/python3.4/site-packages/werkzeug/local.py", line 338, in __getattr__
==> default:     return getattr(self._get_current_object(), name)
==> default: AttributeError: '_AppCtxGlobals' object has no attribute 'eor_db'

**Comment by jrnorth** [comment]
I suspect this error is happening because you're testing locally without the MWA_DB_USERNAME and MWA_DB_PW environment variables set to their respective values. Try setting them and re-running it.

**Comment by dhganey** [comment]
Confirmed -- error occurs due to missing environment var login values.
