### ISSUE TITLE
Fix/Modify observation+error bar names

### ISSUE THREAD

**Issue by ryandougherty** [dhganey/mwa-capstone#21]
![screen shot 2015-02-04 at 11 08 37 am](https://cloud.githubusercontent.com/assets/4794145/6046328/49105308-ac5e-11e4-8f16-b1bb314161de.png)

When selecting a larger range, the ids for the bar names are quite cumbersome. I suggest either making them sideways or some other shorter format (or both!)

**Comment by dhganey** [comment]
@jrnorth, the new histogram avoids this issue right?

**Comment by jrnorth** [comment]
Yes, it's no longer a problem.
