### ISSUE TITLE
Add tabbed view for tables after clicking on histogram

### ISSUE THREAD

**Issue by ryandougherty** [dhganey/mwa-capstone#23]
Have some sort of tabbed view where there is only one table visible at a time to make the table look more clean.

**Comment by ryandougherty** [comment]
I think this is done?

**Comment by dhganey** [comment]
I thought so the other day, but @jrnorth confirmed it's not. This issue refers to the charts which display inside the plot area when user clicks a histogram bar.

That said, he also noted that this would lead to tabs within tabs. Given remaining time on the project and other priorities, I'd vote to close this issue.

**Comment by ryandougherty** [comment]
Alright, closed.
