### ISSUE TITLE
Download sets

### ISSUE THREAD

**Issue by jrnorth** [dhganey/mwa-capstone#40]
Users should be able to download a set as a text file with one "good" obs_id per line.

**Comment by ryandougherty** [comment]
Could we possibly improve this? When a user downloads a set, there is a lot of redundancy in the beginning of the obs id.

Possibly we could implement a trie idea because of this to save space:

1023
1024
1025
1026
1027

translates to:

102 {
3
4
5
6
7
}

**Comment by jrnorth** [comment]
Danny said that this is the way the researchers currently do things - they work with lists of obs ids. Since we're including this feature so that researchers can continue to do work the way they're accustomed to doing it, we should leave it as-is.

**Comment by ryandougherty** [comment]
Oh yeah, I forgot about that. Thanks!
