### ISSUE TITLE
Set URLs in comments don't hyperlink

### ISSUE THREAD

**Issue by dhganey** [dhganey/mwa-capstone#43]
Comments should suggest set names and automatically insert pretty links to them.

![screen shot 2015-03-20 at 13 47 44](https://cloud.githubusercontent.com/assets/6125193/6760617/c83acebc-cf07-11e4-9d88-801ca297a30d.png)

**Comment by ryandougherty** [comment]
Proposed solution (something along these lines): 

import re
import urlparse

url = "This is some text with http://www.google.com some urls"
words = url.split()
fixed = []
for string in words:
	if urlparse.urlparse(string).geturl().startswith('http'):
		# it is a url
		string = "<a href=\"" + string + "\">" + string + "</a>"
	fixed.append(string)

print fixed

**Comment by ryandougherty** [comment]
Damn github comments do not show spaces haha

**Comment by jrnorth** [comment]
Fixed by https://github.com/dhganey/mwa-capstone/commit/fe4d514f2d1f9dff9bc02fcccd6d14c335f0fae6
