### ISSUE TITLE
Set hyperlinking does not support apostrophes

### ISSUE THREAD

**Issue by dhganey** [dhganey/mwa-capstone#70]
This is minor, but see below:

![1](https://cloud.githubusercontent.com/assets/6125193/7305388/5329239c-e9b2-11e4-86b3-ab253dec20ae.PNG)

![2](https://cloud.githubusercontent.com/assets/6125193/7305389/55068434-e9b2-11e4-99a1-1655daaf2172.PNG)

**Comment by jrnorth** [comment]
It's apostrophes. Spaces are fine.

**Comment by dhganey** [comment]
Makes sense! Probably a pretty minimal user impact.

**Comment by jrnorth** [comment]
I'll work on a fix for this later today.

**Comment by ryandougherty** [comment]
I tested the function itself on strings with a single quote - are we passing strings into it with double quotes or with single ones? That may be why.

**Comment by jrnorth** [comment]
Whatever solution we have, it should work with both single quotes and double quotes.

**Comment by ryandougherty** [comment]
I think it has to do with the jinja safe filter: https://github.com/dhganey/mwa-capstone/blob/fe4d514f2d1f9dff9bc02fcccd6d14c335f0fae6/eorlive_prototype/app/templates/comments_list.html#L18 (it autoescapes the HTML)

**Comment by dhganey** [comment]
Well, safe is telling it to allow HTML. That's why the links work. I think it's the processing in the filter?

**Comment by ryandougherty** [comment]
This is what I get in the output: <a href='/set/Danny's test test' target='_blank'>Danny's test test</a>

So it is that the href is supposed to be 2 quotes, not 1. I'll fix it now.

**Comment by jrnorth** [comment]
I think this would be a better solution: https://docs.python.org/2/library/urllib.html#urllib.quote

**Comment by ryandougherty** [comment]
That can be better - I fixed it for now so we can just use what we have now.

**Comment by ryandougherty** [comment]
We will eventually have to escape double quotes in the output string but that is the only case that does not work so far I think.
