### ISSUE TITLE
500 error on user deletion

### ISSUE THREAD

**Issue by dhganey** [dhganey/mwa-capstone#71]
This is my fault. I tried to delete a user on the Heroku site. I get a 500 response, but I'm not sure why.

![screen shot 2015-04-23 at 22 11 23](https://cloud.githubusercontent.com/assets/6125193/7312790/013c6770-ea06-11e4-88e0-967e10a1ff19.png)

Strangely, this does not always happen. It does not seem to be dependent on choosing "transfer" vs "destroy," but it is inconsistent -- I was able to delete one user without error, but most throw this 500 error.

**Comment by ryandougherty** [comment]
Which user were you able to delete without the 500?

**Comment by dhganey** [comment]
One of the Connor users, connor@connor.com I think.

**Comment by jrnorth** [comment]
Let me check the logs.

**Comment by jrnorth** [comment]
Hm, there isn't anything useful there.

**Comment by dhganey** [comment]
Damn... Thanks! Was just about to ask you to do that. Heroku doesn't show a spitout from the Python error?

**Comment by jrnorth** [comment]
Apparently not. I imagine it would, but perhaps you need to configure that explicitly.

**Comment by ryandougherty** [comment]
Maybe it has to do with the username and email being the same? Maybe check if there is an incorrect assignment to a variable somewhere.

**Comment by benhroos** [comment]
Haha maybe it knows that it's not a real email.

**Comment by dhganey** [comment]
No, I don't think so... 500 means a programming error, but my code is so simple. I just reread the delete_user function, and it totally looks right....

**Comment by ryandougherty** [comment]
Yeah I can't find anything wrong with it either. And it seems to work for one user, so I'm not sure what is going on.

**Comment by dhganey** [comment]
It could be a Jinja error in the user_page.html template, but I don't see any errors with that as well. And I tested this fairly extensively, the feature has worked until now. @jrnorth, is it possible it's a database capacity thing? I can't imagine how, but perhaps we've exceeded the number of DB calls we can make?

**Comment by dhganey** [comment]
Closed by #73
